project/mod_admin/controllers.py
import os

from flask import Blueprint, render_template, flash, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from project.mod_admin.forms import ProductCreateForm
from project.models import Order

admin_blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@admin_blueprint.route('orders')
@login_required
def orders():
    all_orders = Order.query.all()
    return render_template('admin/orders.html', all_orders=all_orders, current_user=current_user)


@admin_blueprint.route('/products/create', methods=['GET', 'POST'])
@login_required
def products_create():
    form_products_create = ProductCreateForm()
    if form_products_create.validate_on_submit():
        filename = secure_filename(form_products_create.Photo.data.filename)
        path_to_uploads = os.path.join(current_app.config['BASE_DIR'], 'project', 'uploads', filename)
        form_products_create.Photo.data.save(path_to_uploads)
        flash('Товар додано. %s !' % form_products_create.Title)
    return render_template('admin/products-create.html', form_products_create=form_products_create)

project/mod_auth/controllers.py
import datetime

from flask import Blueprint, request, render_template, flash, session, redirect, url_for
from flask_jwt_extended import create_access_token
from flask_login import login_user, logout_user, login_required
from sqlalchemy import or_

from project import db
from project.mod_auth.forms import SignUpForm, LoginForm
from project.models import User

# Define the blueprint: 'auth', set its url prefix: app.url/auth
# auth_blueprint = Blueprint('auth', __name__, url_prefix='/auth')
auth_blueprint = Blueprint('auth', __name__)


@auth_blueprint.route('/signin', methods=['GET', 'POST'])
def signin():
    users_demo = User.query.all()
    login_form = LoginForm(request.form)
    if login_form.validate_on_submit():
        name_or_email = or_(User.UserName == login_form.email.data, User.Email == login_form.email.data)
        user = User.query.filter(name_or_email).one_or_none()
        if user and user.check_password(login_form.password.data):
            login_user(user, remember=login_form.remember)
            expires = datetime.timedelta(days=7)
            access_token = create_access_token(identity=user, expires_delta=expires)
            session['debug_access_token'] = access_token
            flash(f'Ласкаво просимо, {user.UserName}!')
            return redirect(url_for('main.profile'))
        flash('Невірний логін або пароль', 'error-message')
    return render_template('auth/signin.html', all_users=users_demo, login_form=login_form)


@auth_blueprint.route('/signout')
@login_required
def signout():
    session.pop('_flashes', None)
    logout_user()
    return redirect(url_for('auth.signin'))


@auth_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    signup_form = SignUpForm(request.form)
    if signup_form.validate_on_submit():
        existing_user = User.query.filter_by(Email=signup_form.email.data).first()
        if existing_user:
            flash(f'Email {existing_user.Email} вже використовується!')
            return redirect(url_for('auth.signup'))
        # create new user with the form data. Hash the password so plaintext version isn't saved.
        new_user = User.from_signup(
            name=signup_form.username.data,
            password=signup_form.password.data,
            email=signup_form.email.data)

        db.session.add(new_user)
        db.session.commit()
        flash(f'Користувача {new_user.Email} зареєстровано')
        return redirect(url_for('auth.signin'))
    return render_template('auth/signup.html', signup_form=signup_form)

project/mod_main/controllers.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from sqlalchemy import join

from project.mod_main.forms import FilterProductsForm
from project.models import Order, Category, User, AttributesByCategory, Manufacturer

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/')
def index():
    return render_template('index.html')


@main_blueprint.route('/configurator')
@login_required
def configurator():
    filter_form = FilterProductsForm()
    filters = Category.query.all()
        #.outerjoin(Category.attributes_by_categories) \
        #.outerjoin(AttributesByCategory.Attribute) \
        #.all()
    manufacturers = Manufacturer.query.all()
    all_categories = Category.query.all()
    return render_template('main/configurator.html',
                           allCategories=all_categories,
                           filter_form=filter_form,
                           filters=filters,
                           manufacturers=manufacturers
                           )


@main_blueprint.route('/katalog')
@login_required
def katalog():
    return render_template('main.html')


@main_blueprint.route('/profile')
@login_required
def profile():
    return render_template('main/profile.html', current_user=current_user)


@main_blueprint.route('/myorders')
@login_required
def myorders():
    ###

    my_orders = Order.query. \
        join(User, User.id == Order.CreatedBy). \
        filter(User.id == current_user.id). \
        all()

    ### add check if there is no orders
    return render_template('main/myorders.html', my_orders=my_orders, current_user=current_user)

project/templates/about.html
{% extends 'base.html' %}
{% block title %}
 <title>shop</title>
{% endblock %}

{% block body %}


    <!-- ====== Banner Start ====== -->
    <section class="ud-page-banner">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-banner-content">
              <h1>About Page</h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Banner End ====== -->

    <!-- ====== About Start ====== -->
    <section id="about" class="ud-about">
      <div class="container">
        <div class="ud-about-wrapper wow fadeInUp" data-wow-delay=".2s">
          <div class="ud-about-content-wrapper">
            <div class="ud-about-content">
              <span class="tag">About Us</span>
              <h2>Brilliant Toolkit to Build Nextgen Website Faster.</h2>
              <p>
                The main ‘thrust’ is to focus on educating attendees on how to
                best protect highly vulnerable business applications with
                interactive panel discussions and roundtables led by subject
                matter experts.
              </p>

              <p>
                The main ‘thrust’ is to focus on educating attendees on how to
                best protect highly vulnerable business applications with
                interactive panel.
              </p>
              <a href="javascript:void(0)" class="ud-main-btn">Learn More</a>
            </div>
          </div>
          <div class="ud-about-image">
            <img src="static/images/about/about-image.svg" alt="about-image" />
          </div>
        </div>
      </div>
    </section>
    <!-- ====== About End ====== -->

    <!-- ====== Team Start ====== -->
    <section id="team" class="ud-team">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-section-title mx-auto text-center">
              <span>Our Team</span>
              <h2>Meet The Team</h2>
              <p>
                There are many variations of passages of Lorem Ipsum available
                but the majority have suffered alteration in some form.
              </p>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-3 col-lg-3 col-sm-6">
            <div class="ud-single-team wow fadeInUp" data-wow-delay=".1s">
              <div class="ud-team-image-wrapper">
                <div class="ud-team-image">
                  <img src="static/images/team/team-01.png" alt="team" />
                </div>

                <img
                  src="static/images/team/dotted-shape.svg"
                  alt="shape"
                  class="shape shape-1"
                />
                <img
                  src="static/images/team/shape-2.svg"
                  alt="shape"
                  class="shape shape-2"
                />
              </div>
              <div class="ud-team-info">
                <h5>Adveen Desuza</h5>
                <h6>UI Designer</h6>
              </div>
              <ul class="ud-team-socials">
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-facebook-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-twitter-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-instagram-filled"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-sm-6">
            <div class="ud-single-team wow fadeInUp" data-wow-delay=".15s">
              <div class="ud-team-image-wrapper">
                <div class="ud-team-image">
                  <img src="static/images/team/team-02.png" alt="team" />
                </div>

                <img
                  src="static/images/team/dotted-shape.svg"
                  alt="shape"
                  class="shape shape-1"
                />
                <img
                  src="static/images/team/shape-2.svg"
                  alt="shape"
                  class="shape shape-2"
                />
              </div>
              <div class="ud-team-info">
                <h5>Jezmin uniya</h5>
                <h6>Product Designer</h6>
              </div>
              <ul class="ud-team-socials">
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-facebook-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-twitter-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-instagram-filled"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-sm-6">
            <div class="ud-single-team wow fadeInUp" data-wow-delay=".2s">
              <div class="ud-team-image-wrapper">
                <div class="ud-team-image">
                  <img src="static/images/team/team-03.png" alt="team" />
                </div>

                <img
                  src="static/images/team/dotted-shape.svg"
                  alt="shape"
                  class="shape shape-1"
                />
                <img
                  src="static/images/team/shape-2.svg"
                  alt="shape"
                  class="shape shape-2"
                />
              </div>
              <div class="ud-team-info">
                <h5>Andrieo Gloree</h5>
                <h6>App Developer</h6>
              </div>
              <ul class="ud-team-socials">
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-facebook-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-twitter-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-instagram-filled"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-sm-6">
            <div class="ud-single-team wow fadeInUp" data-wow-delay=".25s">
              <div class="ud-team-image-wrapper">
                <div class="ud-team-image">
                  <img src="static/images/team/team-04.png" alt="team" />
                </div>

                <img
                  src="static/images/team/dotted-shape.svg"
                  alt="shape"
                  class="shape shape-1"
                />
                <img
                  src="static/images/team/shape-2.svg"
                  alt="shape"
                  class="shape shape-2"
                />
              </div>
              <div class="ud-team-info">
                <h5>Jackie Sanders</h5>
                <h6>Content Writer</h6>
              </div>
              <ul class="ud-team-socials">
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-facebook-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-twitter-filled"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/MusharofChy">
                    <i class="lni lni-instagram-filled"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Team End ====== -->


{% endblock %}

project/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lineicons.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/ud-styles.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}"/>
</head>

<body>
<!-- ====== Header Start ====== -->
<header class="ud-header customheader">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg">
                    <a class="navbar-brand" href="/">
                        <img src="/static/images/logo/logo.svg" alt="Logo"/>
                    </a>
                    <button class="navbar-toggler">
                        <span class="toggler-icon"> </span>
                        <span class="toggler-icon"> </span>
                        <span class="toggler-icon"> </span>
                    </button>

                    <div class="navbar-collapse">
                        <ul id="nav" class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a href="{{ url_for('main.index') }}" class="ud-menu-scroll"> Головна </a>
                            </li>
                            <li class="nav-item">
                                <a class="ud-menu-scroll" href="/#about"> Про нас </a>
                            </li>
                            <li class="nav-item">
                                <a class="ud-menu-scroll" href="/#faq">Питання/відповіді</a>
                            </li>
                            <li class="nav-item">
                                <a class="ud-menu-scroll" href="/#contact">Контакти</a>
                            </li>
                            <li class="nav-item nav-item-has-children">
                                <a href="javascript:void(0)"> Каталог </a>
                                <ul class="ud-submenu">
                                    <li class="ud-submenu-item">
                                        <a href="{{ url_for('main.katalog') }}" class="navbar-item"> Каталог </a>
                                    </li>
                                    <li class="ud-submenu-item">
                                        <a href="{{ url_for('main.configurator') }}" class="navbar-item">
                                            Конфігуратор </a>
                                    </li>
                                    <li class="ud-submenu-item">
                                        {% if current_user.is_authenticated %}
                                        <a href="{{ url_for('main.myorders') }}" class="navbar-item">
                                            Мої замовлення
                                        </a>
                                        {% endif %}
                                    </li>
                                </ul>
                            </li>

                            {% if current_user.is_authenticated %}
                            {% if current_user.is_admin() %}
                            <li class="nav-item nav-item-has-children">
                                <a href="javascript:void(0)"> Адмін </a>
                                <ul class="ud-submenu">
                                    <li class="ud-submenu-item">
                                        <a href="{{ url_for('admin.products_create') }}" class="navbar-item">
                                            Додати товар
                                        </a>
                                    </li>
                                    <li class="ud-submenu-item">
                                        <a href="{{ url_for('admin.orders') }}" class="navbar-item">
                                            Усі замовлення
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            {% endif %}
                            {% endif %}
                        </ul>
                    </div>

                    <div class="navbar-btn d-none d-sm-inline-block">

                        {% if not current_user.is_authenticated %}
                        <a href="{{ url_for('auth.signin') }}" class="ud-main-btn ud-login-btn">
                            Авторизація
                        </a>
                        <a href="{{ url_for('auth.signup') }}" class="ud-main-btn ud-login-btn">
                            Реєстрація
                        </a>
                        {% endif %}


                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.signout') }}" class="ud-main-btn ud-white-btn">
                            Вихід
                        </a>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('main.profile') }}" class="ud-main-btn ud-white-btn">
                            Профіль
                        </a>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ====== Header End ====== -->
{% block content %}
{% endblock %}
<div class="container">
    <div class="row">
        <div class="col">
            <code>
                Token: {{ session['debug_access_token'] }}
            </code>
        </div>

    </div>
</div>
<!-- ====== Back To Top Start ====== -->
<a href="javascript:void(0)" class="back-to-top">
    <i class="lni lni-chevron-up"> </i>
</a>
<!-- ====== Back To Top End ====== -->

<!-- ====== All Javascript Files ====== -->
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% block scripts %}
{% endblock %}
</body>

</html>

project/templates/base1.html
{% extends "base.html" %}


   <!-- ====== Banner Start ====== -->
    <section class="ud-page-banner">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-banner-content">
              {% block title1 %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Banner End ====== -->
 {% block content %}
               {% endblock %}

project/templates/macros.html
{% macro render_accordion_item(key, header) -%}
<div class="accordion-item">
    <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button"
                data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-{{key}}"
                aria-expanded="false" aria-controls="panelsStayOpen-{{key}}">
            {{ header }}
        </button>
    </h2>
    <div class="accordion-collapse collapse"
         id="panelsStayOpen-{{key}}"
         aria-labelledby="panelsStayOpen-{{key}}">
        <div class="accordion-body">
            {{ caller() }}
        </div>
    </div>
</div>
{%- endmacro %}

project/templates/pricing.html
{% extends 'base.html' %}
{% block title %}
 <title>shop</title>
{% endblock %}

{% block content %}
<!-- ====== Banner Start ====== -->
    <section class="ud-page-banner">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="ud-banner-content">
              <h1>Перелік товарів</h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Banner End ====== -->
<main>
<div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
{% for el in data %}
        <div class="col">
          <div class="card shadow-sm">
            {{ el.id_photo }}
            <div class="card-body">
               <div class="ud-pricing-header">
                <h3>{{ el.title }}</h3>
                <h4>{{ el.price }}</h4>
              </div>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
{% endfor %}
      </div>
    </div>
  </div>

    </main>
 {% endblock %}